Repository logto-io/kotlin, pull requests merged in 2022-04, with the labels that each got.

#135 refactor(core): use `login` as the value of the `prompt` in generate sign in uri
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/PromptValue.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
Labels: enhancement

#136 feat: enforce trailing-comma style rule
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/session/LogtoAuthSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/webview/WebViewAuthActivity.kt
  build-logic/detekt/src/main/kotlin/io.logto.detekt.gradle.kts
  build-logic/detekt/src/main/resources/detekt.yml
  gradle/libs.versions.toml
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpGet.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpPost.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/CallbackUriUtils.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/CodeTokenResponseTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/IdTokenClaimsTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/OidcConfigResponseTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/RefreshTokenTokenResponseTest.kt
Labels: feature

#132 feat(android-sdk): social native sign in
  .gitignore
  android-sample-java/app/src/main/res/values/logto.xml
  android-sample-kotlin/app/build.gradle.kts
  android-sample-kotlin/app/src/main/AndroidManifest.xml
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/MainActivity.kt
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/fragment/LoginFragment.kt
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/fragment/TokenFragment.kt
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/viewmodel/LogtoViewModel.kt
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/viewmodel/LogtoViewModelFactory.kt
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/wxapi/WXEntryActivity.kt
  android-sample-kotlin/app/src/main/res/navigation/nav_host.xml
  android-sample-kotlin/app/src/main/res/values/logto.xml
  android-sdk/android/build.gradle.kts
  android-sdk/android/src/main/AndroidManifest.xml
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/CallbackUriActivity.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/LogtoAuthManager.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthManager.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthActivity.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthClient.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/session/AuthSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/session/WebAuthSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/web/WebSocialResultActivity.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivity.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/webview/WebViewAuthClient.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/webview/WebViewSocialHandler.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/exception/LogtoException.kt
  android-sdk/android/src/main/res/values/logto.xml
  android-social/alipay/build.gradle.kts
  android-social/settings.gradle.kts
  gradle/libs.versions.toml
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/PromptValue.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
  settings.gradle.kts
Labels: feature

#137 feat(android-sdk): detect supported social connectors
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/util/LogtoUtils.kt
Labels: feature

#139 feat(android-sdk): handle social error
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialException.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/completion/Completion.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
Labels: feature

#140 feat(android-sdk): align callback uri scheme
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
Labels: feature

#138 ci: update workflow
  .github/workflows/update-metadata.yml
Labels: size/s

#142 test(android-sdk): add test for logto utils
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/util/LogtoUtils.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/util/LogtoUtilsTest.kt
Labels: testing, size/s

#143 test(android-sdk): add ut for logto auth session
  android-sdk/android/build.gradle.kts
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
  gradle/libs.versions.toml
Labels: testing, size/l

#144 test(android-sdk): add ut for social session helper
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelperTest.kt
Labels: testing, size/s

#145 test(android-sdk): add ut for logto auth manager
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthManager.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthManagerTest.kt
Labels: testing, size/s

#146 test(android-sdk): add ut for storage key
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/constant/StorageKeyTest.kt
Labels: testing, size/s

#147 test(android-sdk): add ut for logto config extension
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/extension/LogtoConfigExtKtTest.kt
Labels: testing, size/s

#148 test(andorid-sdk): add ut for access token type
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/type/AccessTokenTest.kt
Labels: testing, size/s

#149 test(android-sdk): add ut for logto webview social handler
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
Labels: testing, size/l

#153 test(android-sdk): add ut for logto webview auth activity
  android-sdk/android/build.gradle.kts
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthActivity.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthActivityTest.kt
  gradle/libs.versions.toml
Labels: testing, size/s

#151 feat(android-sdk): use uri constructor to construct oidc config endpoint
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/extension/LogtoConfigExt.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/extension/LogtoConfigExtKtTest.kt
Labels: feature, size/s

#150 test(android-sdk): post social exception
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
Labels: testing, size/s

#152 test(android-sdk): add ut for logto webview auth client
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthClient.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthClientTest.kt
Labels: testing, size/s

#141 test(core): add missing tests for core
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/constant/ConstantTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/extension/JwtClaimsExtKtTest.kt
Labels: testing, size/s

#156 test(android-sdk): web social result activity
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/web/WebSocialResultActivity.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/web/WebSocialResultActivityTest.kt
Labels: testing, size/s

#154 test(android-sdk): web social session
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSession.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSessionTest.kt
Labels: testing, size/m

#155 test(android-sdk): alipay social session
  android-sdk/android/build.gradle.kts
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSessionTest.kt
Labels: testing, size/m

#159 test(android-sdk): wechat social result activity
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivity.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivityTest.kt
Labels: testing, size/m

#161 test(android-sdk): persist storage
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/storage/PersistStorageTest.kt
Labels: testing, size/s

#162 feat(core): fetch jwks json
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
Labels: feature, size/l

#163 test(android-sdk): logto client
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
Labels: testing, size/m

#165 refactor(android-sdk): `clientId` -> `appId`
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/viewmodel/LogtoViewModel.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/extension/LogtoConfigExtKtTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/type/LogtoConfigTest.kt
Labels: enhancement, size/s

#166 feat: suppress long params list style check
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  build-logic/detekt/src/main/resources/detekt.yml
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
Labels: feature, size/xs

#169 feat(core): deployment
  kotlin-sdk/kotlin/build.gradle.kts
Labels: feature, size/s
