Repository logto-io/kotlin, pull requests merged in 2022-05, with the labels that each got.

#167 refactor: align test description
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthManagerTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthClientTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelperTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivityTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/type/AccessTokenTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/util/LogtoUtilsTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/extension/JwtClaimsExtKtTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/CodeTokenResponseTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/IdTokenClaimsTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/OidcConfigResponseTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/RefreshTokenTokenResponseTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/UserInfoResponseTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/CallbackUriUtilsTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/GenerateUtilsTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/TokenUtilsTest.kt
Labels: enhancement, size/m

#171 refactor(android-sdk): `signInWithBrowser` -> `signIn`
  android-sample-java/app/src/main/java/io/logto/demo4j/fragment/LoginFragment.java
  android-sample-java/app/src/main/java/io/logto/demo4j/viewmodel/LogtoViewModel.java
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/fragment/LoginFragment.kt
  android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/viewmodel/LogtoViewModel.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
Labels: enhancement, size/s

#170 feat(android-sdk): deployment
  android-sdk/android/build.gradle.kts
Labels: feature, size/s

#173 feat: deploy sdks to maven central
  android-sdk/android/build.gradle.kts
  gradle/libs.versions.toml
  kotlin-sdk/kotlin/build.gradle.kts
Labels: feature, size/s

#174 refactor: exceptions
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/exception/LogtoException.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/exception/CallbackUriVerificationException.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/exception/ResponseException.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/exception/UriConstructionException.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpGet.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpPost.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/CallbackUriUtils.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/CallbackUriUtilsTest.kt
Labels: enhancement, size/m

#175 docs(android-sdk): logto client
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
Labels: size/s

#177 chore: remove reduplicate repository declaration
  build-logic/settings.gradle.kts
Labels: chore, size/xs

#176 docs: logto core utils
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/CallbackUriUtils.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/ScopeUtils.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/TokenUtils.kt
Labels: size/s

#178 docs: add readme
  README.md
  logo.png
Labels: size/s

#179 refactor(android-sdk): `connector id` -> `connector target` and `callback scheme` -> `callback link`
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelperTest.kt
Labels: enhancement, size/s

#180 chore: update LICENSE
  LICENSE
Labels: chore, size/l

#181 fix(android-sdk): navigate to alipay app in android 11
  android-sdk/android/src/main/AndroidManifest.xml
Labels: bugfix, size/xs

#182 feat(android-sdk): update native and logto ui convention
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelperTest.kt
Labels: feature, size/s

#183 fix(android-sdk): native social auth state
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivity.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSessionTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivityTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSessionTest.kt
Labels: bugfix, size/m

#185 fix(android-sdk): disable web view activity configuration change
  android-sdk/android/src/main/AndroidManifest.xml
Labels: bugfix, size/xs

#186 feat(android-sdk): forward all alipay auth results
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSessionTest.kt
Labels: feature, size/s
