Repository logto-io/kotlin, pull requests merged in 2022-07, with the labels that each got.

#190 feat: remove userinfo related stuff
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/ClaimName.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/extension/JwtClaimsExt.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/IdTokenClaims.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/OidcConfigResponse.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/UserInfoResponse.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/extension/JwtClaimsExtKtTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/IdTokenClaimsTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/OidcConfigResponseTest.kt
  kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/UserInfoResponseTest.kt
Labels: feature, size/l

#193 fix(android-sdk): using persist storage by default
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
Labels: bugfix, size/xs

#192 fix(android-sdk): role names should only contain not-null string value
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/IdTokenClaims.kt
Labels: bugfix, size/xs

#194 feat: update build info
  android-sample-java/app/build.gradle.kts
  android-sample-java/settings.gradle.kts
  android-sample-kotlin/app/build.gradle.kts
  android-sample-kotlin/settings.gradle.kts
  android-sdk/android/build.gradle.kts
  android-sdk/settings.gradle.kts
  android-social/alipay/build.gradle.kts
  android-social/settings.gradle.kts
  gradle/libs.versions.toml
  gradle/logto.versions.toml
  kotlin-sdk/kotlin/build.gradle.kts
  kotlin-sdk/settings.gradle.kts
Labels: feature, size/s

#195 chore: update README
  README.md
Labels: chore, size/xs

#196 chore: fix README
  README.md
Labels: chore, size/s

#198 chore: use default community health files
  .github/pull_request_template.md
Labels: chore, size/s

#197 feat: read resource from access token
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/TokenUtils.kt
Labels: feature, size/s
