Repository logto-io/kotlin, pull requests merged in 2023-10, with the labels that each got.

#216 fix(core): Fix `ResponseException::responseContent` population
  kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt
Labels: bugfix

#218 chore: update build version to `1.1.0`
  gradle/logto.versions.toml
Labels: chore, size/xs

#219 feat(android-sdk): support copy text for WebView
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthActivity.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewPolyfill.kt
  android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
  android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
Labels: feature, size/s
